name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build (Angular prod)
        run: npm run build --if-present

      - name: Inject runtime env.js
        run: |
          mkdir -p dist/weather-dashboard/browser
          echo "window.__env = { OWM_API_KEY: '${{ secrets.OWM_API_KEY }}' };" > dist/weather-dashboard/browser/env.js

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_HILL_09A4D861E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: dist/weather-dashboard/browser
          output_location: ""
          skip_app_build: true
